ai-generated-tweet-to-kafka-service:
  streaming-data-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  ai-service: SpringAI-OpenAI
  scheduler-duration-sec: 30
  prompt: "Generate a json with 4 elements called createdAt, id, text and user. The user element has also a nested json element called id. For createdA use a date in format 'EEE MMM dd HH:mm:ss zzz yyy', example date would be 'Fri Oct 06 14:32:25 UTC 2026', for id use a Java long value, for text use a String including one or more of the keywords: {keywords}. For id field of the user field use a Java long value. Do not write anything on the response other than the JSON text. That means omit ```json part in the response and any other explanation. Do not include the L letter at the end of the long values. Only give one result in the response."
  keywords-placeholder: "{keywords}"
  open-ai:
    url: "https://api.openai.com/v1/chat/completions"
    api-key: ${OPENAI_API_KEY}
    content-type: "application/json"
    model: "gpt-4o-mini"
    max-completion-tokens: 150
    temperature: 1
    messages:
      - role: "user"
        content:
          -
            type: "text"
  google-gen-ai:
    projectId: ""
    location: "us-west-1"
    modelName: "gemini-2.0-flash-001"
    max-output-tokens: 150
    temperature: 1
    candidate-count: 1

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
#      api-key: ${DEEPSEEK_API_KEY}
      base-url: "https://api.openai.com"
#      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: "gpt-4o-mini"
#          model: "deepseek-chat"
          temperature: 1
          maxTokens: 150
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:14b
          temperature: 1
          max-new-tokens: 150

retry-config:
  initial-interval-ms: 1000
  max-interval: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-name
  num-of-partitions: 3
  replication-factor: 3

